version: '3.3' # specify docker-compose version

# Define the services/containers to be run
services:
  mongodb: 
    image: mongo 
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
  demo:
    image: hantsy/spring-native-demo
    environment:
      - "SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/blog"
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
volumes:
  mongodata: