name: build-image

on:
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - master

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Docker Image
        run: mvn clean spring-boot:build-image -DskipTests -Pnative-image

      - name: Set up MongoDb
        run: |
          docker-compose up -d mongodb
          docker ps -a

      - name: Run app in Docker Container
        run: docker run --rm demo:0.0.1-SNAPSHOT
      
      - name: Run FunctionalTests
        run: |
          mvn clean verify      
