name: build-native-image

on:
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - master

jobs:
  build-native-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - uses: DeLaGuardo/setup-graalvm@4.0
        with:
          # GraalVM version, no pattern syntax available atm
          graalvm: '21.0.0.2'
          # Java version, optional, defaults to 'java8'. Available options are 'java8' and 'java11'.
          java: 'java11'
          # Architecture flag, optional, defaults to 'amd64'. Available options are 'amd64' and 'aarch64'. Later is available only for linux runners.
          arch: 'amd64'
      - run: java -version
      - name: Install native-image component
        run: |
          gu install native-image

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set up MongoDB
        run: |
          docker-compose up -d mongodb
          sleep 10
          docker ps -a

      - name: Build Native Image and Run Application
        run: |
          mvn clean package -DskipTests -Pspring-native,build-native-image
          ./target/com.example.demo.demoapplication &
          sleep 10

      - name: Run FunctionalTests
        run: |
          mvn test -Pfunctional-test
